package nmf;

import model.TopicRiver;

public class TopicTimeTracker
{
  public static void main(String[] args)
  {
    String xmlInputPath;
    boolean writeCSV = false;
    boolean writeJSON = false;

    if (args.length != 3)
    {
      printUsage();
      return;
    }
    else
    {
      xmlInputPath = args[0];
      if (args[1].equals("1"))
      {
        writeCSV = true;
      }
      if (args[2].equals("1"))
      {
        writeJSON = true;
      }
    }

    TopicRiver tr = TopicRiver.loadTopicRiver(xmlInputPath);
    if (tr == null)
    {
      System.out.println("Visualization data cannot be generated.");
      return;
    }

    System.out.println(tr);
    if (writeCSV)
    {
      VisualizationDataConverter.writeCSVData(tr, "output.csv");
    }
    if (writeJSON)
    {
      VisualizationDataConverter.writeJSONData(tr);
    }
  }

  private static void printUsage()
  {
    System.out.println("TopicTimeTracker:");
    System.out.println("Used to generate visualization data out of the nmf data xml files.");
    System.out.println("java -jar TopicTimeTracker <inputpath> <writeCSV> <writeJSON>");
    System.out.println("inputpath (Path) - defines the path to a directory where the XML files generated by NMFTopicExtractor are contained. These XML files, each representing the topics of a certain time span, are then loaded into a topic river.");
    System.out.println("writeCSV (int) - if \"1\", CSV visualization data will be written. This is the more advanced visualization tool.");
    System.out.println("writeJSON (int) - if \"1\", JSON visualization data will be written.");
  }
}
